### ISSUE TITLE
Set up user authentication

### ISSUE THREAD

**Issue by jakobnunnendorf** [jakobnunnendorf/shop#1]

**Comment by jakobnunnendorf** [comment]
@hamzaiqbal2000 can you write a high level summary for this as well?

**Comment by jakobnunnendorf** [comment]
https://supabase.com/docs/reference/javascript/auth-signup

**Comment by hamzaiqbal2000** [comment]
Steps:
First, setup redux or context API on the nextJs app.
After that you can send a request on this endpoint for creating/sign up a new User:
const { data, error } = await supabase.auth.signUp({
  email: 'example@email.com',
  password: 'example-password',
})

No need to store the returned data for signup in context/redux

So for User authentication you need to send a request to this endpoint:
const { data, error } = await supabase.auth.getSession()
This will return a token which you can use for authentication. You can store the token in cookies or local storage.
Now you can store the users auth value( which would be true when the user is logged in and session returns a token) in the context state, and this is how you can easily access the auth state(if user is logged in or not) in the whole application easily without passing it in props.

Now for furthur requests you have to send this token attached in the headers with each subsequent request.

**Comment by jakobnunnendorf** [comment]
Perfect think i can take it from here. Will probably have results tomorrow.
