### ISSUE TITLE
Set up redux for global state management

### ISSUE THREAD

**Issue by jakobnunnendorf** [jakobnunnendorf/shop#5]
@hamzaiqbal2000 Can you write a high level summary of the steps that need to be taken to use Redux for global state management?

**Comment by jakobnunnendorf** [comment]
Also what kind of information should we store in global state?

**Comment by jakobnunnendorf** [comment]
Recoil seems easy to use https://recoiljs.org/docs/introduction/getting-started what do you think of this as an option?

**Comment by hamzaiqbal2000** [comment]
> Also what kind of information should we store in global state?

The kind of information that we need to use in different components in different parts of application, for example, for user authentication we need to user a data field auth in the global state that would track if the user has logined or not, and other information can stored like states for edit and add forms cause they would share common form code and state

**Comment by hamzaiqbal2000** [comment]
> Recoil seems easy to use https://recoiljs.org/docs/introduction/getting-started what do you think of this as an option?

Ok lemme review the documentation and then we can see if it is a better choice or not.

**Comment by hamzaiqbal2000** [comment]
> @hamzaiqbal2000 Can you write a high level summary of the steps that need to be taken to use Redux for global state management?

For redux, there are 3 main components, first one is actions, 2nd one is Reducer functions and 3rd one is store. They interact with each other where we can store data in redux store and then retrieve it. Reducer functions are like switch statements which take an action object(contrains type and payload properties) and then decide which switch statement would run based on the type property and any payload contains data that needs to be added to redux. We can send actions to reducer functions using useDispatch hook, and retreieve data using useSelector

Steps:
First setup redux by creating a store in the index.js file.
After that create a file for storing the reducer functions.
After that create a file for storing the actions
Now you can create a reducer function according to your requirements to store the data based on a type(action object) condition

**Comment by jakobnunnendorf** [comment]
I think when calling supabase login function it returns either user data or error and we can easily implement if else logic updating userRole state depending on response > > Also what kind of information should we store in global state?
> 
> 
> 
> The kind of information that we need to use in different components in different parts of application, for example, for user authentication we need to user a data field auth in the global state that would track if the user has logined or not, and other information can stored like states for edit and add forms cause they would share common form code and state
> 
>

**Comment by jakobnunnendorf** [comment]
I read about the unnecessary rerenders but I think context is probably enough and seems very easy to use. If necessary I'm willing to update to redux in the future end. > > @hamzaiqbal2000 Can you write a high level summary of the steps that need to be taken to use Redux for global state management?
> 
> 
> 
> For redux, there are 3 main components, first one is actions, 2nd one is Reducer functions and 3rd one is store. They interact with each other where we can store data in redux store and then retrieve it. Reducer functions are like switch statements which take an action object(contrains type and payload properties) and then decide which switch statement would run based on the type property and any payload contains data that needs to be added to redux. We can send actions to reducer functions using useDispatch hook, and retreieve data using useSelector
> 
> 
> 
> Steps:
> 
> First setup redux by creating a store in the index.js file.
> 
> After that create a file for storing the reducer functions.
> 
> After that create a file for storing the actions
> 
> Now you can create a reducer function according to your requirements to store the data based on a type(action object) condition

**Comment by jakobnunnendorf** [comment]
What do you mean by add forms? > add forms cause they would share common form code and state

**Comment by hamzaiqbal2000** [comment]
> I read about the unnecessary rerenders but I think context is probably enough and seems very easy to use. If necessary I'm willing to update to redux in the future end. > > @hamzaiqbal2000 Can you write a high level summary of the steps that need to be taken to use Redux for global state management?
> 
> > For redux, there are 3 main components, first one is actions, 2nd one is Reducer functions and 3rd one is store. They interact with each other where we can store data in redux store and then retrieve it. Reducer functions are like switch statements which take an action object(contrains type and payload properties) and then decide which switch statement would run based on the type property and any payload contains data that needs to be added to redux. We can send actions to reducer functions using useDispatch hook, and retreieve data using useSelector
> > Steps:
> > First setup redux by creating a store in the index.js file.
> > After that create a file for storing the reducer functions.
> > After that create a file for storing the actions
> > Now you can create a reducer function according to your requirements to store the data based on a type(action object) condition

yeah context would be good enough for this type of project.

**Comment by hamzaiqbal2000** [comment]
> What do you mean by add forms? > add forms cause they would share common form code and state

like add and edit form for any entity, like for example if we have to add/edit products, they would share the state and form fields but logic for sending the data to the backend would be different for both.
